[config]

[templates.hyprland]
input_path = './templates/hyprland-colors.conf'
output_path = '~/.config/hypr/colors.conf'
post_hook = 'hyprctl reload'

[templates.waybar]
input_path = './templates/waybar.css'
output_path = '~/.config/waybar/colors.css'
post_hook = 'pkill -SIGUSR2 waybar'


[templates.kitty]
input_path = './templates/kitty-colors.conf'
output_path = '~/.config/kitty/colors.conf'
post_hook = 'pkill -SIGUSR1 kitty'


[templates.pywalfox]
input_path = './templates/pywalfox-colors.json'
output_path = '~/.cache/wal/colors.json'
post_hook = 'pywalfox update'


[templates.btop]
input_path = './templates/btop.theme'
output_path = '~/.config/btop/themes/matugen.theme'


[templates.wlogout]
input_path = './templates/waybar.css'
output_path = '~/.config/wlogout/colors.css'


[templates.swaync]
input_path = './templates/waybar.css'
output_path = '~/.config/swaync/colors.css'
post_hook = 'swaync-client -rs'

[templates.tmux]
input_path = './templates/tmux-colors.conf'
output_path = '~/.config/tmux/generated.conf'
post_hook = 'tmux source-file ~/.config/tmux/generated.conf'

[templates.fuzzel]
input_path = './templates/fuzzel.ini'
output_path = '~/.config/fuzzel/colors.ini'


[templates.cava]
input_path = './templates/cava-colors.ini'
output_path = '~/.config/cava/themes/matugen'
post_hook = 'pkill -USR1 cava'

